"""Initial migration

Revision ID: d565118f6bcc
Revises: 
Create Date: 2025-12-08 18:20:10.672424

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd565118f6bcc'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('courseId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('courseId')
    )
    op.create_table('users',
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('STUDENT', 'TEACHER', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('courseId', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['courseId'], ['courses.courseId'], ),
    sa.PrimaryKeyConstraint('userId')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('apps',
    sa.Column('appId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=True),
    sa.Column('git_link', sa.String(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('appId')
    )
    op.create_table('deployments',
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='deploymentstatus'), nullable=True),
    sa.Column('commitHash', sa.String(), nullable=True),
    sa.Column('commitInfo', sa.Text(), nullable=True),
    sa.Column('userInputVar', sa.Text(), nullable=True),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('appId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['apps.appId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('deploymentId')
    )
    op.create_table('user_groups',
    sa.Column('userGroupId', sa.UUID(), nullable=False),
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], ),
    sa.PrimaryKeyConstraint('userGroupId'),
    sa.UniqueConstraint('deploymentId')
    )
    op.create_table('course_to_user_groups',
    sa.Column('courseToUserGroupID', sa.UUID(), nullable=False),
    sa.Column('courseId', sa.UUID(), nullable=False),
    sa.Column('userGroupId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['courses.courseId'], ),
    sa.ForeignKeyConstraint(['userGroupId'], ['user_groups.userGroupId'], ),
    sa.PrimaryKeyConstraint('courseToUserGroupID')
    )
    op.create_table('teams',
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('userGroupId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['userGroupId'], ['user_groups.userGroupId'], ),
    sa.PrimaryKeyConstraint('teamId')
    )
    op.create_table('user_to_user_groups',
    sa.Column('userToUserGroupId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('userGroupId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['userGroupId'], ['user_groups.userGroupId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('userToUserGroupId')
    )
    op.create_table('user_to_teams',
    sa.Column('userToTeamId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('teamId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['teamId'], ['teams.teamId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('userToTeamId')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_to_teams')
    op.drop_table('user_to_user_groups')
    op.drop_table('teams')
    op.drop_table('course_to_user_groups')
    op.drop_table('user_groups')
    op.drop_table('deployments')
    op.drop_table('apps')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
