"""Add Task table and celeryTaskId

Revision ID: 922872ac64c5
Revises: d565118f6bcc
Create Date: 2025-12-30 16:01:43.052523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '922872ac64c5'
down_revision: Union[str, None] = 'd565118f6bcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tasks',
    sa.Column('taskId', sa.UUID(), nullable=False),
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.Column('celeryTaskId', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('DEPLOY', 'UPDATE', 'DESTROY', 'PAUSE', 'RESUME', name='tasktype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', 'CANCELLED', name='taskstatus'), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('logs', sa.Text(), nullable=True),
    sa.Column('tf_state', sa.Text(), nullable=True),
    sa.Column('outputs', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], ),
    sa.PrimaryKeyConstraint('taskId')
    )
    op.add_column('deployments', sa.Column('releaseTag', sa.String(), nullable=True))
    op.drop_column('deployments', 'commitInfo')
    op.drop_column('deployments', 'commitHash')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deployments', sa.Column('commitHash', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('deployments', sa.Column('commitInfo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('deployments', 'releaseTag')
    op.drop_table('tasks')
    # ### end Alembic commands ###
