"""add app_version_approvals and is_private to apps

Revision ID: cd8fc0985a36
Revises: a7b8c9d0e1f2
Create Date: 2026-06-16 10:29:55.814602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd8fc0985a36'
down_revision: Union[str, None] = 'a7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_version_approvals',
    sa.Column('approvalId', sa.UUID(), nullable=False),
    sa.Column('appId', sa.UUID(), nullable=False),
    sa.Column('version_tag', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='appversionapprovalstatus'), nullable=False),
    sa.Column('diff_url', sa.String(), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appId'], ['apps.appId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.userId'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('approvalId'),
    sa.UniqueConstraint('appId', 'version_tag', name='uq_app_version_approval')
    )
    op.create_index(op.f('ix_app_version_approvals_appId'), 'app_version_approvals', ['appId'], unique=False)
    op.create_index(op.f('ix_app_version_approvals_reviewed_by'), 'app_version_approvals', ['reviewed_by'], unique=False)
    op.add_column('apps', sa.Column('is_private', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'is_private')
    op.drop_index(op.f('ix_app_version_approvals_reviewed_by'), table_name='app_version_approvals')
    op.drop_index(op.f('ix_app_version_approvals_appId'), table_name='app_version_approvals')
    op.drop_table('app_version_approvals')
    # ### end Alembic commands ###
