"""add_notes_to_app_version_approvals

Revision ID: b320979d7cd5
Revises: 0e43dd2bc856
Create Date: 2026-06-26 12:05:12.072437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b320979d7cd5'
down_revision: Union[str, None] = '0e43dd2bc856'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_version_approvals', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_version_approvals', 'notes')
    # ### end Alembic commands ###
