"""course to teacher

Revision ID: 8a6766f6326b
Revises: b320979d7cd5
Create Date: 2026-06-27 11:27:44.491053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a6766f6326b'
down_revision: Union[str, None] = 'b320979d7cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_teachers',
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.courseId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.userId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('course_id', 'user_id')
    )
    op.create_index(op.f('ix_course_teachers_user_id'), 'course_teachers', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_course_teachers_user_id'), table_name='course_teachers')
    op.drop_table('course_teachers')
    # ### end Alembic commands ###
