"""remove dep status and update user group idea

Revision ID: 39b084214589
Revises: 922872ac64c5
Create Date: 2026-01-10 17:02:39.477123

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39b084214589'
down_revision: Union[str, None] = '922872ac64c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Drop FK constraints on user_groups FIRST
    op.drop_constraint('course_to_user_groups_userGroupId_fkey', 'course_to_user_groups', type_='foreignkey')
    op.drop_constraint('user_to_user_groups_userGroupId_fkey', 'user_to_user_groups', type_='foreignkey')
    op.drop_constraint(op.f('teams_userGroupId_fkey'), 'teams', type_='foreignkey')
    
    # Step 2: Now drop the dependent tables
    op.drop_table('course_to_user_groups')
    op.drop_table('user_to_user_groups')
    op.drop_table('user_groups')
    
    # Step 3: Update teams table
    op.add_column('teams', sa.Column('deploymentId', sa.UUID(), nullable=True))
    op.drop_column('teams', 'userGroupId')
    # Set deploymentId to NOT NULL after update (if needed, update existing rows first)
    op.alter_column('teams', 'deploymentId', nullable=False)
    op.create_foreign_key(None, 'teams', 'deployments', ['deploymentId'], ['deploymentId'])
    
    # Step 4: Create the new user_to_deployments table
    op.create_table('user_to_deployments',
    sa.Column('userToDeploymentId', sa.UUID(), nullable=False),
    sa.Column('userId', sa.UUID(), nullable=False),
    sa.Column('deploymentId', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], ),
    sa.PrimaryKeyConstraint('userToDeploymentId')
    )
    
    # Step 5: Remove status column from deployments
    op.drop_column('deployments', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('userGroupId', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'teams', type_='foreignkey')
    op.create_foreign_key(op.f('teams_userGroupId_fkey'), 'teams', 'user_groups', ['userGroupId'], ['userGroupId'])
    op.drop_column('teams', 'deploymentId')
    op.add_column('deployments', sa.Column('status', postgresql.ENUM('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='deploymentstatus'), autoincrement=False, nullable=True))
    op.create_table('user_groups',
    sa.Column('userGroupId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('deploymentId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['deploymentId'], ['deployments.deploymentId'], name='user_groups_deploymentId_fkey'),
    sa.PrimaryKeyConstraint('userGroupId', name='user_groups_pkey'),
    sa.UniqueConstraint('deploymentId', name='user_groups_deploymentId_key', postgresql_include=[], postgresql_nulls_not_distinct=False),
    postgresql_ignore_search_path=False
    )
    op.create_table('course_to_user_groups',
    sa.Column('courseToUserGroupID', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('courseId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('userGroupId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['courseId'], ['courses.courseId'], name=op.f('course_to_user_groups_courseId_fkey')),
    sa.ForeignKeyConstraint(['userGroupId'], ['user_groups.userGroupId'], name=op.f('course_to_user_groups_userGroupId_fkey')),
    sa.PrimaryKeyConstraint('courseToUserGroupID', name=op.f('course_to_user_groups_pkey'))
    )
    op.create_table('user_to_user_groups',
    sa.Column('userToUserGroupId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('userId', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('userGroupId', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['userGroupId'], ['user_groups.userGroupId'], name=op.f('user_to_user_groups_userGroupId_fkey')),
    sa.ForeignKeyConstraint(['userId'], ['users.userId'], name=op.f('user_to_user_groups_userId_fkey')),
    sa.PrimaryKeyConstraint('userToUserGroupId', name=op.f('user_to_user_groups_pkey'))
    )
    op.drop_table('user_to_deployments')
    # ### end Alembic commands ###
