"""redeploy

Revision ID: 73fd123a60aa
Revises: cd8fc0985a36
Create Date: 2026-06-24 14:48:16.969096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73fd123a60aa'
down_revision: Union[str, None] = 'cd8fc0985a36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apps', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_apps_live'), table_name='apps', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('ix_deployments_live'), table_name='deployments', postgresql_where='(deleted_at IS NULL)')
    op.drop_index(op.f('uq_tasks_active_per_deployment'), table_name='tasks', postgresql_where="(status = ANY (ARRAY['PENDING'::taskstatus, 'RUNNING'::taskstatus]))")
    op.drop_constraint(op.f('uq_user_openstack_credentials_userId'), 'user_openstack_credentials', type_='unique')
    op.drop_index(op.f('ix_user_openstack_credentials_userId'), table_name='user_openstack_credentials')
    op.create_index(op.f('ix_user_openstack_credentials_userId'), 'user_openstack_credentials', ['userId'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_openstack_credentials_userId'), table_name='user_openstack_credentials')
    op.create_index(op.f('ix_user_openstack_credentials_userId'), 'user_openstack_credentials', ['userId'], unique=False)
    op.create_unique_constraint(op.f('uq_user_openstack_credentials_userId'), 'user_openstack_credentials', ['userId'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('uq_tasks_active_per_deployment'), 'tasks', ['deploymentId'], unique=True, postgresql_where="(status = ANY (ARRAY['PENDING'::taskstatus, 'RUNNING'::taskstatus]))")
    op.create_index(op.f('ix_deployments_live'), 'deployments', ['deploymentId'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.create_index(op.f('ix_apps_live'), 'apps', ['appId'], unique=False, postgresql_where='(deleted_at IS NULL)')
    op.alter_column('apps', 'is_private',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    # ### end Alembic commands ###
